name: iOS-ipa-build
on:
  workflow_dispatch:

# FIX: Grant write permission
permissions:
  contents: write

jobs:
  build-ios:
    name: ðŸŽ‰ iOS Build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      - run: flutter pub get
        working-directory: money_tracker

      - run: pod repo update
        working-directory: money_tracker/ios

      - run: flutter build ios --release --no-codesign
        working-directory: money_tracker

      - run: mkdir Payload
        working-directory: money_tracker/build/ios/iphoneos

      - run: mv Runner.app/ Payload
        working-directory: money_tracker/build/ios/iphoneos

      # Zipping with project name
      - name: Zip output
        run: zip -qq -r -9 money_tracker.ipa Payload
        working-directory: money_tracker/build/ios/iphoneos

      # Uploading with permissions fixed
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: money_tracker/build/ios/iphoneos/money_tracker.ipa
          tag: v1.${{ github.run_number }} # I recommend using run_number to avoid "Tag already exists" errors
          overwrite: true
          body: "Build number: ${{ github.run_number }}"
