name: Deploy Flutter Web
on:
  workflow_dispatch: # Allows manual trigger

permissions:
  contents: write # Required to push to the gh-pages branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - run: flutter pub get
        working-directory: money_tracker

      # IMPORTANT: We use the repository name as the base-href
      # If your repo url is github.com/user/my-app, the base-href must be /my-app/
      - name: Build Web
        run: flutter build web --release --base-href "/${{ github.event.repository.name }}/"
        working-directory: money_tracker

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: money_tracker/build/web # Uploads only the web build folder
          force_orphan: true # Keeps the history clean (optional)
