name: iOS-ipa-build
on:
  workflow_dispatch:

jobs:
  build-ios:
    name: ðŸŽ‰ iOS Build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      - run: flutter pub get
        working-directory: money_tracker

      - run: pod repo update
        working-directory: money_tracker/ios

      - run: flutter build ios --release --no-codesign
        working-directory: money_tracker

      - run: mkdir Payload
        working-directory: money_tracker/build/ios/iphoneos

      - run: mv Runner.app/ Payload
        working-directory: money_tracker/build/ios/iphoneos

      # CHANGE 1: Update the zip name here
      - name: Zip output
        run: zip -qq -r -9 money_tracker.ipa Payload
        working-directory: money_tracker/build/ios/iphoneos

      # CHANGE 2: Update the file path to match the new name here
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: money_tracker/build/ios/iphoneos/money_tracker.ipa
          # v1 is hardcoded, run_number changes automatically (e.g., v1.55)
          tag: v1.${{ github.run_number }}
          release_name: "Release v1.${{ github.run_number }}"
          overwrite: true
          body: "Build number: ${{ github.run_number }}"
